In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
data=pd.read_csv('/content/superstore_messy_dataset.csv')

In [ ]:
data

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,ORD-1,2021-04-13,2023-08-14,Standard Class,CUST-5510,Rahul,Corporate,India,Delhi,WB,North,PROD-420,Office Supplies,Chairs,Item A,1084.46,6,NaN,-18.78
1,ORD-2,2022-03-12,2021-10-08,Standard Class,CUST-1393,Rahul,Corporate,India,Mumbai,WB,East,PROD-441,Technology,Binders,Item C,4576.87,2,0.46,-1274.67
2,ORD-3,2023-05-11,2021-09-10,Standard Class,CUST-9005,Amit,Consumer,India,Bangalore,MH,South,PROD-127,Office Supplies,Storage,Item C,764.96,8,0.31,-74.58
3,ORD-4,2021-09-28,2021-11-08,First Class,CUST-4686,Arjun,Consumer,India,Kolkata,DL,North,PROD-413,Office Supplies,Phones,Item D,1522.06,4,0.02,134.90
4,ORD-5,2021-04-17,2022-12-23,First Class,CUST-1357,Sneha,Home Office,India,Kolkata,DL,East,PROD-314,Furniture,Chairs,Item B,1060.52,6,0.41,-276.86
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10195,ORD-8954,2022-10-27,2021-12-01,First Class,CUST-3508,Amit,Corporate,India,Bangalore,KA,South,PROD-516,Technology,Storage,Item C,2060.48,2,0.13,116.45
10196,ORD-4922,2022-01-05,2022-05-06,Second Class,CUST-7345,Amit,Consumer,India,Bangalore,WB,North,PROD-346,Office Supplies,Storage,Item B,4678.69,4,0.36,-800.04
10197,ORD-5512,2022-09-05,2021-03-10,First Class,CUST-9151,Sneha,Home Office,India,Kolkata,DL,South,PROD-653,Technology,Storage,Item A,2493.12,5,0.21,-40.60
10198,ORD-2620,2021-01-24,2021-04-30,First Class,CUST-9805,Sneha,Corporate,India,Mumbai,DL,North,PROD-723,Furniture,Phones,Item B,2147.98,4,0.17,5.86
10199,ORD-1114,2021-12-01,2023-09-29,Standard Class,CUST-9572,Neha,Corporate,India,Delhi,WB,North,PROD-218,Furniture,Binders,Item B,4074.46,8,0.41,NaN

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10200 entries, 0 to 10199
Data columns (total 19 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order ID       10200 non-null  object
 1   Order Date     10200 non-null  object
 2   Ship Date      10200 non-null  object
 3   Ship Mode      10200 non-null  object
 4   Customer ID    10200 non-null  object
 5   Customer Name  10200 non-null  object
 6   Segment        10200 non-null  object
 7   Country        10200 non-null  object
 8   City           9687 non-null   object
 9   State          10200 non-null  object
 10  Region         10200 non-null  object
 11  Product ID     10200 non-null  object
 12  Category       10200 non-null  object
 13  Sub-Category   10200 non-null  object
 14  Product Name   10200 non-null  object
 15  Sales          9690 non-null   float64
 16  Quantity       10200 non-null  int64
 17  Discount       9691 non-null   float64
 18  Profit         9686 non-null   float64
dtypes: float64(3), int64(1), object(15)
memory usage: 1.5+ MB

In [ ]:
data.duplicated().any()

np.True_

In [ ]:
data.duplicated().sum ()

np.int64(196)

In [ ]:
data.isnull().sum()

Order ID           0
Order Date         0
Ship Date          0
Ship Mode          0
Customer ID        0
Customer Name      0
Segment            0
Country            0
City             513
State              0
Region             0
Product ID         0
Category           0
Sub-Category       0
Product Name       0
Sales            510
Quantity           0
Discount         509
Profit           514
dtype: int64

In [ ]:
data.describe()

             Sales      Quantity     Discount       Profit
count  9690.000000  10200.000000  9691.000000  9686.000000
mean   2545.628851      4.966961     0.251417  -130.549307
std    1431.455178      2.571687     0.144310   429.654109
min      50.890000      1.000000     0.000000 -1519.240000
25%    1291.402500      3.000000     0.120000  -377.815000
50%    2570.385000      5.000000     0.250000   -75.060000
75%    3805.920000      7.000000     0.370000   122.482500
max    4999.340000      9.000000     0.500000  1068.880000

In [ ]:
#remove all duplicates value from data permanently

data.drop_duplicates(inplace=True)

In [ ]:
numarical={'Sales','Discount','Profit'}
for i in categorical:
  data[i].fillna(data[i].median(),inplace=True)

NameError: name 'categorical' is not defined

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10004 entries, 0 to 10157
Data columns (total 19 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order ID       10004 non-null  object
 1   Order Date     10004 non-null  object
 2   Ship Date      10004 non-null  object
 3   Ship Mode      10004 non-null  object
 4   Customer ID    10004 non-null  object
 5   Customer Name  10004 non-null  object
 6   Segment        10004 non-null  object
 7   Country        10004 non-null  object
 8   City           9504 non-null   object
 9   State          10004 non-null  object
 10  Region         10004 non-null  object
 11  Product ID     10004 non-null  object
 12  Category       10004 non-null  object
 13  Sub-Category   10004 non-null  object
 14  Product Name   10004 non-null  object
 15  Sales          9504 non-null   float64
 16  Quantity       10004 non-null  int64
 17  Discount       9504 non-null   float64
 18  Profit         9504 non-null   float64
dtypes: float64(3), int64(1), object(15)
memory usage: 1.5+ MB

In [ ]:
data['City'].fillna(data['City'].mode()[0],inplace=True)

/tmp/ipykernel_13451/3489286642.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['City'].fillna(data['City'].mode()[0],inplace=True)

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10004 entries, 0 to 10157
Data columns (total 19 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order ID       10004 non-null  object
 1   Order Date     10004 non-null  object
 2   Ship Date      10004 non-null  object
 3   Ship Mode      10004 non-null  object
 4   Customer ID    10004 non-null  object
 5   Customer Name  10004 non-null  object
 6   Segment        10004 non-null  object
 7   Country        10004 non-null  object
 8   City           10004 non-null  object
 9   State          10004 non-null  object
 10  Region         10004 non-null  object
 11  Product ID     10004 non-null  object
 12  Category       10004 non-null  object
 13  Sub-Category   10004 non-null  object
 14  Product Name   10004 non-null  object
 15  Sales          9504 non-null   float64
 16  Quantity       10004 non-null  int64
 17  Discount       9504 non-null   float64
 18  Profit         9504 non-null   float64
dtypes: float64(3), int64(1), object(15)
memory usage: 1.5+ MB

In [ ]:
data

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,ORD-1,2021-04-13,2023-08-14,Standard Class,CUST-5510,Rahul,Corporate,India,Delhi,WB,North,PROD-420,Office Supplies,Chairs,Item A,1084.46,6,NaN,-18.78
1,ORD-2,2022-03-12,2021-10-08,Standard Class,CUST-1393,Rahul,Corporate,India,Mumbai,WB,East,PROD-441,Technology,Binders,Item C,4576.87,2,0.46,-1274.67
2,ORD-3,2023-05-11,2021-09-10,Standard Class,CUST-9005,Amit,Consumer,India,Bangalore,MH,South,PROD-127,Office Supplies,Storage,Item C,764.96,8,0.31,-74.58
3,ORD-4,2021-09-28,2021-11-08,First Class,CUST-4686,Arjun,Consumer,India,Kolkata,DL,North,PROD-413,Office Supplies,Phones,Item D,1522.06,4,0.02,134.90
4,ORD-5,2021-04-17,2022-12-23,First Class,CUST-1357,Sneha,Home Office,India,Kolkata,DL,East,PROD-314,Furniture,Chairs,Item B,1060.52,6,0.41,-276.86
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9999,ORD-10000,2021-10-02,2022-08-09,Standard Class,CUST-1459,Sneha,Corporate,India,Delhi,DL,South,PROD-104,Technology,Phones,Item B,3961.92,9,0.28,-320.77
10028,ORD-8013,2021-10-12,2022-10-16,Second Class,CUST-5751,Arjun,Corporate,India,Bangalore,DL,South,PROD-281,Furniture,Phones,Item C,2898.85,1,0.15,118.65
10078,ORD-7580,2022-06-08,2023-09-11,Second Class,CUST-1130,Priya,Home Office,India,Delhi,KA,South,PROD-719,Technology,Binders,Item C,4516.24,8,0.12,360.31
10119,ORD-8378,2022-12-01,2023-05-20,Second Class,CUST-3122,Priya,Consumer,India,Kolkata,DL,South,PROD-136,Furniture,Chairs,Item A,1151.69,5,0.15,89.72
10157,ORD-1250,2021-08-02,2021-05-22,Standard Class,CUST-7323,Amit,Home Office,India,Delhi,MH,East,PROD-472,Office Supplies,Chairs,Item D,637.68,9,0.13,42.78

In [ ]:

data['Order Date']=pd.to_datetime(data['Order Date'])

In [ ]:
data['Ship Date']=pd.to_datetime(data['Ship Date'])

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10004 entries, 0 to 10157
Data columns (total 19 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order ID       10004 non-null  object
 1   Order Date     10004 non-null  datetime64[ns]
 2   Ship Date      10004 non-null  datetime64[ns]
 3   Ship Mode      10004 non-null  object
 4   Customer ID    10004 non-null  object
 5   Customer Name  10004 non-null  object
 6   Segment        10004 non-null  object
 7   Country        10004 non-null  object
 8   City           10004 non-null  object
 9   State          10004 non-null  object
 10  Region         10004 non-null  object
 11  Product ID     10004 non-null  object
 12  Category       10004 non-null  object
 13  Sub-Category   10004 non-null  object
 14  Product Name   10004 non-null  object
 15  Sales          9504 non-null   float64
 16  Quantity       10004 non-null  int64
 17  Discount       9504 non-null   float64
 18  Profit         9504 non-null   float64
dtypes: datetime64[ns](2), float64(3), int64(1), object(13)
memory usage: 1.8+ MB

In [ ]:
data['Month']=data['Order Date'].dt.month

In [ ]:
data

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Month
0,ORD-1,2021-04-13,2023-08-14,Standard Class,CUST-5510,Rahul,Corporate,India,Delhi,WB,North,PROD-420,Office Supplies,Chairs,Item A,1084.46,6,NaN,-18.78,4
1,ORD-2,2022-03-12,2021-10-08,Standard Class,CUST-1393,Rahul,Corporate,India,Mumbai,WB,East,PROD-441,Technology,Binders,Item C,4576.87,2,0.46,-1274.67,3
2,ORD-3,2023-05-11,2021-09-10,Standard Class,CUST-9005,Amit,Consumer,India,Bangalore,MH,South,PROD-127,Office Supplies,Storage,Item C,764.96,8,0.31,-74.58,5
3,ORD-4,2021-09-28,2021-11-08,First Class,CUST-4686,Arjun,Consumer,India,Kolkata,DL,North,PROD-413,Office Supplies,Phones,Item D,1522.06,4,0.02,134.90,9
4,ORD-5,2021-04-17,2022-12-23,First Class,CUST-1357,Sneha,Home Office,India,Kolkata,DL,East,PROD-314,Furniture,Chairs,Item B,1060.52,6,0.41,-276.86,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9999,ORD-10000,2021-10-02,2022-08-09,Standard Class,CUST-1459,Sneha,Corporate,India,Delhi,DL,South,PROD-104,Technology,Phones,Item B,3961.92,9,0.28,-320.77,10
10028,ORD-8013,2021-10-12,2022-10-16,Second Class,CUST-5751,Arjun,Corporate,India,Bangalore,DL,South,PROD-281,Furniture,Phones,Item C,2898.85,1,0.15,118.65,10
10078,ORD-7580,2022-06-08,2023-09-11,Second Class,CUST-1130,Priya,Home Office,India,Delhi,KA,South,PROD-719,Technology,Binders,Item C,4516.24,8,0.12,360.31,6
10119,ORD-8378,2022-12-01,2023-05-20,Second Class,CUST-3122,Priya,Consumer,India,Kolkata,DL,South,PROD-136,Furniture,Chairs,Item A,1151.69,5,0.15,89.72,12
10157,ORD-1250,2021-08-02,2021-05-22,Standard Class,CUST-7323,Amit,Home Office,India,Delhi,MH,East,PROD-472,Office Supplies,Chairs,Item D,637.68,9,0.13,42.78,8

In [ ]:
data['year']=data['Order Date'].dt.year

In [ ]:
data

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Month,year
0,ORD-1,2021-04-13,2023-08-14,Standard Class,CUST-5510,Rahul,Corporate,India,Delhi,WB,...,PROD-420,Office Supplies,Chairs,Item A,1084.46,6,NaN,-18.78,4,2021
1,ORD-2,2022-03-12,2021-10-08,Standard Class,CUST-1393,Rahul,Corporate,India,Mumbai,WB,...,PROD-441,Technology,Binders,Item C,4576.87,2,0.46,-1274.67,3,2022
2,ORD-3,2023-05-11,2021-09-10,Standard Class,CUST-9005,Amit,Consumer,India,Bangalore,MH,...,PROD-127,Office Supplies,Storage,Item C,764.96,8,0.31,-74.58,5,2023
3,ORD-4,2021-09-28,2021-11-08,First Class,CUST-4686,Arjun,Consumer,India,Kolkata,DL,...,PROD-413,Office Supplies,Phones,Item D,1522.06,4,0.02,134.90,9,2021
4,ORD-5,2021-04-17,2022-12-23,First Class,CUST-1357,Sneha,Home Office,India,Kolkata,DL,...,PROD-314,Furniture,Chairs,Item B,1060.52,6,0.41,-276.86,4,2021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9999,ORD-10000,2021-10-02,2022-08-09,Standard Class,CUST-1459,Sneha,Corporate,India,Delhi,DL,...,PROD-104,Technology,Phones,Item B,3961.92,9,0.28,-320.77,10,2021
10028,ORD-8013,2021-10-12,2022-10-16,Second Class,CUST-5751,Arjun,Corporate,India,Bangalore,DL,...,PROD-281,Furniture,Phones,Item C,2898.85,1,0.15,118.65,10,2021
10078,ORD-7580,2022-06-08,2023-09-11,Second Class,CUST-1130,Priya,Home Office,India,Delhi,KA,...,PROD-719,Technology,Binders,Item C,4516.24,8,0.12,360.31,6,2022
10119,ORD-8378,2022-12-01,2023-05-20,Second Class,CUST-3122,Priya,Consumer,India,Kolkata,DL,...,PROD-136,Furniture,Chairs,Item A,1151.69,5,0.15,89.72,12,2022
10157,ORD-1250,2021-08-02,2021-05-22,Standard Class,CUST-7323,Amit,Home Office,India,Delhi,MH,...,PROD-472,Office Supplies,Chairs,Item D,637.68,9,0.13,42.78,8,2021

In [ ]:
data['profit margin']=data['Profit']/data['Sales']

In [ ]:
data['sales category']=pd.cut(data['Sales'],
                              bins=[0,100,500,1000,5000],
                              labels=['low','medium','high','very high'])

In [ ]:
data

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,...,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Month,year,profit margin,sales category
0,ORD-1,2021-04-13,2023-08-14,Standard Class,CUST-5510,Rahul,Corporate,India,Delhi,WB,...,Chairs,Item A,1084.46,6,NaN,-18.78,4,2021,-0.017317,very high
1,ORD-2,2022-03-12,2021-10-08,Standard Class,CUST-1393,Rahul,Corporate,India,Mumbai,WB,...,Binders,Item C,4576.87,2,0.46,-1274.67,3,2022,-0.278503,very high
2,ORD-3,2023-05-11,2021-09-10,Standard Class,CUST-9005,Amit,Consumer,India,Bangalore,MH,...,Storage,Item C,764.96,8,0.31,-74.58,5,2023,-0.097495,high
3,ORD-4,2021-09-28,2021-11-08,First Class,CUST-4686,Arjun,Consumer,India,Kolkata,DL,...,Phones,Item D,1522.06,4,0.02,134.90,9,2021,0.088630,very high
4,ORD-5,2021-04-17,2022-12-23,First Class,CUST-1357,Sneha,Home Office,India,Kolkata,DL,...,Chairs,Item B,1060.52,6,0.41,-276.86,4,2021,-0.261061,very high
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9999,ORD-10000,2021-10-02,2022-08-09,Standard Class,CUST-1459,Sneha,Corporate,India,Delhi,DL,...,Phones,Item B,3961.92,9,0.28,-320.77,10,2021,-0.080963,very high
10028,ORD-8013,2021-10-12,2022-10-16,Second Class,CUST-5751,Arjun,Corporate,India,Bangalore,DL,...,Phones,Item C,2898.85,1,0.15,118.65,10,2021,0.040930,very high
10078,ORD-7580,2022-06-08,2023-09-11,Second Class,CUST-1130,Priya,Home Office,India,Delhi,KA,...,Binders,Item C,4516.24,8,0.12,360.31,6,2022,0.079781,very high
10119,ORD-8378,2022-12-01,2023-05-20,Second Class,CUST-3122,Priya,Consumer,India,Kolkata,DL,...,Chairs,Item A,1151.69,5,0.15,89.72,12,2022,0.077903,very high
10157,ORD-1250,2021-08-02,2021-05-22,Standard Class,CUST-7323,Amit,Home Office,India,Delhi,MH,...,Chairs,Item D,637.68,9,0.13,42.78,8,2021,0.067087,high

In [ ]:
#which catagori has the highest total sales?
#which catagori gives most profitable?
#how many nagetive trasaction they have
#monthly sales treand
#which customer segments contributs most in sales?
#which city genarate highest sales?
#profit by regions
#sales catagori distribution

In [ ]:
data.to_csv('clean superstore.csv',index=False)